### ISSUE TITLE
Readme should preview result for Object.create(null)

### ISSUE THREAD

**Issue by mk-pmb** [Xotic750/safe-to-string-x#2]
… because I wouldn't have expected

> TypeError: Cannot convert object to primitive value

If that's a bug, please fix it first. :-)

**Comment by Xotic750** [comment]
Thanks for the report. It's because the following throws

`console.log(String(Object.create(null)));`

as there is no method (toString or valueOf) for toPrimitive to convert the object.

`safe-to-string-x` was designed to be safe for use with Symbol Objects and I never took null objects into consideration.

`console.log(String(Object(Symbol(''))));`

I'm not sure whether I should make it safe for null objects, or just document this normal behaviour? I will consider this as an enhancement for now.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#String_conversion

I'm not sure what value one would expect though, perhaps an empty string?

**Comment by Xotic750** [comment]
Added a test that shows that it currently throws and an example to the README. I'm still open to the idea of supporting this in some logical fashion, that compliments the ECMAscript specification.

**Comment by mk-pmb** [comment]
I'm for `[object null]`.

**Comment by Xotic750** [comment]
Looking at this a little more, I'm thinking it may be best to leave as is, as intended, otherwise we start running into other problems like

`console.log(String([Symbol('')]));`

or 

`console.log(String([Object.create(null)]));`

Then safe-to-string-x would need to address issues like this or other exotics, and become some kind of stringify (which could be done probably, if JSON isn't adequate).

So currently to-string-x uses this spec http://www.ecma-international.org/ecma-262/6.0/#sec-tostring and safe-to-string-x is here to deal with the specific part of that spec, where I had need to be able to convert a symbol to a string.

> Symbol | Throw a TypeError exception.

To be honest, this module may be deprecated (have to look at it a little further, not sure),  as is, its name could be confusing if you are looking for some kind of stringify and I should be using the to-primitive-x module as a replacement (maybe) for this (which I hadn't written at my time of need).

https://github.com/Xotic750/to-primitive-x

http://www.ecma-international.org/ecma-262/6.0/#sec-toprimitive

But I'm still open to ideas on this module, it could turn into something else (more) useful.

**Comment by mk-pmb** [comment]
You're right, the array cases blow up complexity quite a bit.

> become some kind of stringify […] if JSON isn't adequate

Sounds like that might turn out as re-inventing [util-inspect](https://www.npmjs.com/package/util-inspect) or [object-inspect](https://www.npmjs.com/package/object-inspect). I'd prefer we only do that if there's a very good reason, to reduce the number of mostly-equivalent packages that will someday litter our projects' dependency trees.

> its name could be confusing if you are looking for some kind of stringify

Yes, highly confusing. My way of fixing it would be (1) a warning at the start of the package description (so it shows up in npm search), and (2) the same or a similar warning near the top of the readme, so it shows up on the npm package details page. Optionally the latter could be followed with a recommendation of other packages.

**Comment by Xotic750** [comment]
I was looking through the spec to see if there was some abstract that could donate its name name this module to be more descriptive. It turns out there is no abstract for this and what this is really doing (save bells and whistles) is the String constructor when used as a function (ie not NewTarget), plus convertion from symbol objects to symbol primitives. So there is no ECMA spec (abstract or otherwise) for what this module is actually doing.

http://www.ecma-international.org/ecma-262/6.0/#sec-string-constructor-string-value

I will see if I can come up with a better name than present, and add some more description.

Perhaps `to-primitive-string-x`?

**Comment by Xotic750** [comment]
I'm going to go with ` to-string-symbols-supported-x` and deprecate this module.

**Comment by Xotic750** [comment]
Hah, browserify doesn't seem to like that name. :(

**Comment by Xotic750** [comment]
https://github.com/Xotic750/to-string-symbols-supported-x

**Comment by Xotic750** [comment]
Now deprecated.
